name: Actions Workout

on: push

jobs:
    numero_uno:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Hello There"
        
        - name: List files
          run: ls -lha

        - name: Read file
          run: cat README.md