name: Actions Workout

on: push

jobs:
    numero_uno:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Hello There"
        
        - name: List files
          run: |
               ls -1a
               ls -1a

        - name: Read file
          run: cat README.md

        - name:  ASCII Art
          run: cowsay -f dragon "Run for cover!!!!!" >> dragon.txt