name: Actions Shell Script

on: push

jobs:

    numero_dos:
        
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Hello There"
        
        - name: Script Permissions
          run: chmod +x test_shell_script.sh
    

        - name: Run Script
          run: ./test_shell_script.sh