name: Multiple Jobs
on: push

jobs:

    build:
        
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install cowsay
          run:  sudo apt-get install cowsay -y
        

    deploy:
        
        needs: build

        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: ASCII Art Populated
          run: 
               cowsay -f dragon "Run for cover!!!!!" >> dragon.txt
               cat dragon.txt


        - uses: actions/download-artifact@v4
          with:
            name: Upload file
            path: dragon.txt


    test:
        needs: deploy

        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - uses: actions/upload-artifact@v4
          with:
            name: Download file
            path: dragon.txt

        - name: 
          run: |
            cat dragon.txt
            echo "File exists!!!"

